# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 11:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateTimeField()),
                ('condition', models.CharField(choices=[('PS', 'Por puesto'), ('FC', 'Auto completo')], default='PS', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('seats', models.IntegerField(null=True)),
                ('arrival_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='rides.Address')),
                ('departure_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='rides.Address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.Vehicle')),
            ],
        ),
    ]
