# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_offer_arrival_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='arrival_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
