# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_auto_20170910_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('Di', 'Disponible'), ('Re', 'Reservado'), ('Ca', 'Cancelado'), ('Re', 'Realizado')], default='Di', max_length=2),
        ),
    ]
