# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_offer_demand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='demand',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='rides.Demand'),
        ),
    ]
