# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0010_auto_20170910_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('PU', 'Publica'), ('PR', 'Privada')], default='PU', max_length=2),
        ),
    ]
