# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0010_auto_20170910_1702'),
        ('rides', '0009_requestpost_offer'),
    ]

    operations = [
    ]
