# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0011_merge_20170910_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='departure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
