# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 18:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0012_auto_20170910_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='departure_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 10, 18, 51, 28, 225131, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
