# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0013_auto_20170910_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpost',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_offer', to='rides.Offer'),
        ),
    ]
