# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0011_offer_offer_type'),
        ('rides', '0014_auto_20170910_1920'),
    ]

    operations = [
    ]
