# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0015_merge_20170910_1920'),
        ('rides', '0012_merge_20170910_1921'),
    ]

    operations = [
    ]
