# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 19:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0016_merge_20170910_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='passenger',
            field=models.ManyToManyField(related_name='my_rides', to=settings.AUTH_USER_MODEL),
        ),
    ]
