# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0018_auto_20170910_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='passenger',
            field=models.ManyToManyField(blank=True, null=True, related_name='passenger_offer', to=settings.AUTH_USER_MODEL),
        ),
    ]
